---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: outbox-statestore
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: localhost:6379
  - name: redisPassword
    value: ""
  - name: outboxPublishPubsub
    value: "pubsub"
  - name: outboxPublishTopic
    value: "my-outbox-topic"
